server:
    port: 8080
javax:
    sql:
        DataSource:
            parkguidanceDataSource:
                dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
                dataSource:
                    url: ${javax.persistence.jdbc.url}
                    user: ${javax.persistence.jdbc.user}
                    password: ${javax.persistence.jdbc.password}
