security:
    providers:
        - custom-jwt:
              publicKeyEndpoint: http://localhost:8080/api/key/activePublicKeys
              isSecurityService: true
server:
    port: 8081
javax:
    sql:
        DataSource:
            parkguidanceDataSource:
                dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
                dataSource:
                    url: jdbc:postgresql://localhost:5432/parkguidance-ms
                    user: DBACC
                    password: DBACC
